---
- hosts: local
  remote_user: root
  tasks:
    - name: test connection
      ping:
    - name: delete whats inside
      shell: "sudo rm -r ~/practice5 -f"
    - name: Retrieving from repo
      git:
        force: yes
        repo: https://github.com/Melody-Tch/Maven-Selenium.git
        dest: ~/practice5

    - name: go to directory and build 
      shell: "cd ~/practice4/devopscdp-ui && ng build && cd"
    - name: send files
      shell: "cd ~/practice4/devopscdp-ui && aws s3 cp dist s3://devopscdp-ui1/ --recursive"

      #note: it ends in an non-zero error code at the end but the application runs perfectly