---
- hosts: servers
  remote_user: root
  tasks:
    - name: test connection
      ping:
    - name: delete whats inside
      shell: "sudo rm -r ~/practice4/devopscdp-ui -f"
    - name: Retrieving from repo
      git:
        force: yes
        repo: https://kenji.a.sato:zero651298@innersource.accenture.com/scm/devopscdp/devopscdp-ui.git
        dest: ~/practice4/devopscdp-ui
    - name: go to directory and build 
      shell: "cd ~/practice4/devopscdp-ui && ng build && cd"
    - name: send files
      shell: "cd ~/practice4/devopscdp-ui && aws s3 cp dist s3://devopscdp-ui1/ --recursive"

      #note: it ends in an non-zero error code at the end but the application runs perfectly